### ISSUE TITLE
Conflict with vscp_goBootloaderMode

### ISSUE THREAD

**Issue by mamac** [grodansparadis/vscp_firmware#4]
Hello,

I just pulled the latest firmware (wanted to push a fix for normalized int...).

When compiling my code for temperature sensor I have the following:
![image](https://cloud.githubusercontent.com/assets/7148802/7146818/76ffa8f8-e2f6-11e4-80ea-e0e21153ed25.png)

I have a line in my code related to goBootloaderMode:
![image](https://cloud.githubusercontent.com/assets/7148802/7146840/9fbfd38a-e2f6-11e4-9e95-0757f74b3976.png)

Since I don't use the bootloader I decided to comment those lines but then I have the following:
![image](https://cloud.githubusercontent.com/assets/7148802/7146859/d1c7ca86-e2f6-11e4-9f9a-abae1ee7430d.png)

Any hint appreciated.
/JM

**Comment by grodansparadis** [comment]
The definition have changed and is now

void vscp_goBootloaderMode( uint8_t algorithm );

Just add a blank implementation in your code if you don't have a bootloader.

void vscp_goBootloaderMode( uint8_t algorithm );
{
     ;
}

/Ake

mamac skrev den 2015-04-14 22:38:
>
> Hello,
>
> I just pulled the latest firmware (wanted to push a fix for normalized 
> int...).
>
> When compiling my code for temperature sensor I have the following:
> image 
> <https://cloud.githubusercontent.com/assets/7148802/7146818/76ffa8f8-e2f6-11e4-80ea-e0e21153ed25.png>
>
> I have a line in my code related to goBootloaderMode:
> image 
> <https://cloud.githubusercontent.com/assets/7148802/7146840/9fbfd38a-e2f6-11e4-9e95-0757f74b3976.png>
>
> Since I don't use the bootloader I decided to comment those lines but 
> then I have the following:
> image 
> <https://cloud.githubusercontent.com/assets/7148802/7146859/d1c7ca86-e2f6-11e4-9f9a-abae1ee7430d.png>
>
> Any hint appreciated.
> /JM
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/4>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by mamac** [comment]
You made my day :-)
Thank you!
