### ISSUE TITLE
Improvement: Node segment initialization visualization handling

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_firmware#5]
The specification says

> It is recommended that some visual indication is shown to indicate success. A blinking green led that turns steady green after a node has got its nickname is the recommended indication. If there is a response for all addresses a failure condition is set (segment full) and the node goes to sleep. 

If the node waits for user interaction regarding starting the initialization, the LED will be off. If you are sitting in front of serveral nodes, which node is waiting, which node is in error state or really off?

Proposal: The LED is blinking slowly in case of waiting for the user to start the initialization. During the node discovery blink fast and after a successful discovered nickname, stay on.

What do you think?

**Comment by grodansparadis** [comment]
Hi Andreas,

good suggestions and I have something like this on some of my nodes.  
Something that is really needed on CAN based nodes is indication for bus 
warnings and bus off.  This cause a lot of problems in the live world. 
My next generation of boards will have a multicolor led or rgb led with 
more posibilities for error indication. The spec just recommend a 
minimum. I think we all should do and implement  what we need above that.

Andreas Merkle skrev den 2015-05-15 14:32:
>
> The specification says
>
>     It is recommended that some visual indication is shown to indicate
>     success. A blinking green led that turns steady green after a node
>     has got its nickname is the recommended indication. If there is a
>     response for all addresses a failure condition is set (segment
>     full) and the node goes to sleep.
>
> If the node waits for user interaction regarding starting the 
> initialization, the LED will be off. If you are sitting in front of 
> serveral nodes, which node is waiting, which node is in error state or 
> really off?
>
> Proposal: The LED is blinking slowly in case of waiting for the user 
> to start the initialization. During the node discovery blink fast and 
> after a successful discovered nickname, stay on.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/5>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by mamac** [comment]
I though about the status led today and wondered if it was possible to
drive the led with a pwm so user can set the intensity of the led.

My nodes have blue leds and are quite powerfull (only 300 ohms resistor
behind). Would be good if I could dim it a bit... The whole house turns
blue during the night :-)

**Comment by BlueAndi** [comment]
@grodansparadis Maybe we increase the minimum recommendation to make peoples life easier and at least having a similar feeling with any kind of vscp nodes.

@mamac Yes, you can use a PWM to dim them in your "blue" house. Greetings from "Blue"Andi ;-)

**Comment by grodansparadis** [comment]
Of course you can. Why not?

mamac skrev den 2015-05-15 18:20:
> I though about the status led today and wondered if it was possible to
> drive the led with a pwm so user can set the intensity of the led.
>
> My nodes have blue leds and are quite powerfull (only 300 ohms resistor
> behind). Would be good if I could dim it a bit... The whole house turns
> blue during the night :-)
> On May 15, 2015 3:34 PM, "Åke Hedman" <notifications@github.com> wrote:
>
> > Hi Andreas,
> >
> > good suggestions and I have something like this on some of my nodes.
> > Something that is really needed on CAN based nodes is indication for bus
> > warnings and bus off. This cause a lot of problems in the live world.
> > My next generation of boards will have a multicolor led or rgb led with
> > more posibilities for error indication. The spec just recommend a
> > minimum. I think we all should do and implement what we need above that.
> >
> > Andreas Merkle skrev den 2015-05-15 14:32:
> > >
> > > The specification says
> > >
> > > It is recommended that some visual indication is shown to indicate
> > > success. A blinking green led that turns steady green after a node
> > > has got its nickname is the recommended indication. If there is a
> > > response for all addresses a failure condition is set (segment
> > > full) and the node goes to sleep.
> > >
> > > If the node waits for user interaction regarding starting the
> > > initialization, the LED will be off. If you are sitting in front of
> > > serveral nodes, which node is waiting, which node is in error state or
> > > really off?
> > >
> > > Proposal: The LED is blinking slowly in case of waiting for the user
> > > to start the initialization. During the node discovery blink fast and
> > > after a successful discovered nickname, stay on.
> > >
> > > What do you think?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/grodansparadis/vscp_firmware/issues/5>.
> > >
> >
> > --
> > Be Hungry - Stay Foolish!
> > Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> > Brattbergavägen 17, 82050 LOS, SWEDEN
> > Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> > http://www.grodansparadis.com http://www.vscp.org
> >
> >
> >
> > ---
> > Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram
> > från Avast.
> > http://www.avast.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_firmware/issues/5#issuecomment-102398496>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/5#issuecomment-102451808>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
Hi,

Specifications are specifications. I which everyone have some indication 
that a node is discovering a nickname and that it is active. From there 
everyone can use there imagination. To specify evey little detail just 
make people doing the opposit anyway. I mean most can't even agree on a 
common bitrate even today.

So if things are possible even without changing the specification I 
think it can stay as it is. If not. Well then it can be worth a change.

/Ake

Andreas Merkle skrev den 2015-05-15 18:54:
>
> @grodansparadis <https://github.com/grodansparadis> Maybe we increase 
> the minimum recommendation to make peoples life easier and at least 
> having a similar feeling with any kind of vscp nodes.
>
> @mamac <https://github.com/mamac> Yes, you can use a PWM to dim them 
> in your "blue" house. Greetings from "Blue"Andi ;-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/issues/5#issuecomment-102457963>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
I know what you mean. Thought it may help, as it helped me ... thererfore decided to push a request.
